/**
 * サイドバーを作成することで、以下を行うことができます：
 - 文書の順序付けられたグループを作成する
 - そのグループの各文書に対してサイドバーをレンダリングする
 - 次/前のナビゲーションを提供する

 サイドバーはファイルシステムから生成することも、ここで明示的に定義することもできます。

 望むだけ多くのサイドバーを作成してください。
 */

const { getGuidesSidebarData } = require('./static/data/guides');

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */

const sidebars = {
  type: 'autogenerated',
  dirName: './whats-new',
};

module.exports = sidebars;